const Products = [
    {
      productId: 1,
      productName: "Pain de campagne",
      category: "Pain",
      categoryId: 1,
      price: "4,50 €",
      quantityInStock: 15,
      description: "Un pain rustique au goût authentique, parfait pour accompagner tous les repas.",
      longDescription: "Le pain de campagne est un classique intemporel, fabriqué à partir d'un mélange de farines de blé et de seigle. Il est cuit lentement pour obtenir une croûte épaisse et croustillante, tandis que l'intérieur reste moelleux. Idéal pour les tartines, les soupes ou simplement accompagné de beurre frais.",
      ingredientList: ["Farine de blé", "Farine de seigle", "Eau", "Levure", "Sel"],
      smallImageUrl: "https://example.com/images/pain_de_campagne_small.jpg",
      bigImageUrl: "https://example.com/images/pain_de_campagne_big.jpg",
      isAvailable: true
    },
    {
      productId: 2,
      productName: "Baguette tradition",
      category: "Pain",
      categoryId: 1,
      price: "1,20 €",
      quantityInStock: 50,
      description: "Une baguette croustillante à l'extérieur et moelleuse à l'intérieur.",
      longDescription: "La baguette tradition est un symbole de la boulangerie française. Avec sa croûte dorée et croustillante et sa mie légère, elle est parfaite pour les sandwichs, les toasts ou tout simplement pour accompagner un repas.",
      ingredientList: ["Farine de blé", "Eau", "Levure", "Sel"],
      smallImageUrl: "https://example.com/images/baguette_tradition_small.jpg",
      bigImageUrl: "https://example.com/images/baguette_tradition_big.jpg",
      isAvailable: true
    },
    {
      productId: 3,
      productName: "Pain complet",
      category: "Pain",
      categoryId: 1,
      price: "3,00 €",
      quantityInStock: 20,
      description: "Riche en fibres, ce pain est idéal pour une alimentation équilibrée.",
      longDescription: "Le pain complet est fabriqué à partir de farine complète, ce qui en fait une source riche en fibres et en nutriments essentiels. Son goût légèrement noisette le rend idéal pour les petits-déjeuners ou les repas équilibrés.",
      ingredientList: ["Farine complète", "Eau", "Levure", "Sel"],
      smallImageUrl: "https://example.com/images/pain_complet_small.jpg",
      bigImageUrl: "https://example.com/images/pain_complet_big.jpg",
      isAvailable: true
    },
    {
      productId: 4,
      productName: "Pain aux noix",
      category: "Pain",
      categoryId: 1,
      price: "5,00 €",
      quantityInStock: 10,
      description: "Un pain savoureux avec des morceaux de noix, parfait pour les fromages.",
      longDescription: "Le pain aux noix est une option gourmande qui associe la douceur du pain à la richesse des noix. Chaque bouchée offre un équilibre parfait entre croquant et moelleux. Idéal pour accompagner les plateaux de fromages ou pour un en-cas nutritif.",
      ingredientList: ["Farine de blé", "Eau", "Levure", "Sel", "Noix"],
      smallImageUrl: "https://example.com/images/pain_aux_noix_small.jpg",
      bigImageUrl: "https://example.com/images/pain_aux_noix_big.jpg",
      isAvailable: false
    },
    {
      productId: 5,
      productName: "Fougasse",
      category: "Pain",
      categoryId: 1,
      price: "4,00 €",
      quantityInStock: 8,
      description: "Une spécialité provençale au parfum d'huile d'olive et d'herbes.",
      longDescription: "La fougasse est un pain plat traditionnel de Provence, souvent parfumé avec des herbes, des olives ou du fromage. Elle est idéale pour les apéritifs, les pique-niques ou simplement comme accompagnement savoureux.",
      ingredientList: ["Farine de blé", "Eau", "Huile d'olive", "Sel", "Herbes de Provence"],
      smallImageUrl: "https://example.com/images/fougasse_small.jpg",
      bigImageUrl: "https://example.com/images/fougasse_big.jpg",
      isAvailable: true
    },
    {
      productId: 6,
      productName: "Pain viennois",
      category: "Pain",
      categoryId: 1,
      price: "2,50 €",
      quantityInStock: 18,
      description: "Un pain légèrement sucré, parfait pour le petit-déjeuner.",
      longDescription: "Le pain viennois est une option douce et moelleuse, légèrement sucrée et souvent agrémentée de pépites de chocolat ou de raisins. Idéal pour accompagner une tasse de thé ou de café au petit-déjeuner.",
      ingredientList: ["Farine de blé", "Beurre", "Lait", "Sucre", "Levure", "Sel"],
      smallImageUrl: "https://example.com/images/pain_viennois_small.jpg",
      bigImageUrl: "https://example.com/images/pain_viennois_big.jpg",
      isAvailable: false
    },
    {
      productId: 7,
      productName: "Pain de seigle",
      category: "Pain",
      categoryId: 1,
      price: "3,80 €",
      quantityInStock: 12,
      description: "Un pain riche et dense avec une saveur unique.",
      longDescription: "Le pain de seigle est fabriqué principalement à partir de farine de seigle, offrant une texture dense et une saveur légèrement acidulée. Idéal pour les amateurs de goûts authentiques, il se marie parfaitement avec les charcuteries et les fromages.",
      ingredientList: ["Farine de seigle", "Eau", "Levure", "Sel"],
      smallImageUrl: "https://example.com/images/pain_de_seigle_small.jpg",
      bigImageUrl: "https://example.com/images/pain_de_seigle_big.jpg",
      isAvailable: true
    },
    {
      productId: 8,
      productName: "Pain brioché",
      category: "Pain",
      categoryId: 11,
      price: "4,20 €",
      quantityInStock: 20,
      description: "Un pain moelleux avec une texture douce et légèrement sucrée.",
      longDescription: "Le pain brioché combine la douceur de la brioche et la légèreté du pain traditionnel. Il est parfait pour les toasts, les sandwichs ou simplement dégusté nature.",
      ingredientList: ["Farine de blé", "Beurre", "Œufs", "Sucre", "Levure", "Lait", "Sel"],
      smallImageUrl: "https://example.com/images/pain_brioche_small.jpg",
      bigImageUrl: "https://example.com/images/pain_brioche_big.jpg",
      isAvailable: true
    },
    {
      productId: 9,
      productName: "Pain aux graines",
      category: "Pain",
      categoryId: 1,
      price: "5,50 €",
      quantityInStock: 10,
      description: "Un pain riche en graines pour une texture et un goût exceptionnels.",
      longDescription: "Le pain aux graines est parsemé d'un mélange de graines comme le sésame, le lin et le tournesol. Parfait pour les amateurs de pains rustiques et nutritifs, il est idéal pour accompagner des salades ou des soupes.",
      ingredientList: ["Farine de blé", "Eau", "Levure", "Sel", "Graines de sésame", "Graines de lin", "Graines de tournesol"],
      smallImageUrl: "https://example.com/images/pain_aux_graines_small.jpg",
      bigImageUrl: "https://example.com/images/pain_aux_graines_big.jpg",
      isAvailable: true
    },
    {
        productId: 10,
        productName: "Pain ciabatta",
        category: "Pain",
        categoryId: 1,
        price: "2,80 €",
        quantityInStock: 18,
        description: "Un pain italien avec une croûte fine et une mie aérée.",
        longDescription: "La ciabatta est un pain italien au goût délicat, avec une texture légère et aérée, parfait pour les paninis.",
        ingredientList: ["Farine de blé", "Levure", "Sel", "Eau", "Huile d'olive"],
        smallImageUrl: "https://example.com/images/pain_ciabatta_small.jpg",
        bigImageUrl: "https://example.com/images/pain_ciabatta_big.jpg",
        isAvailable: false
    },
    {
        productId: 11,
        productName: "Madeleine",
        category: "Delices Sucré",
        categoryId: 2,
        price: "1,00 €",
        quantityInStock: 45,
        description: "Un petit gâteau en forme de coquillage.",
        longDescription: "La madeleine est une pâtisserie française traditionnelle en forme de coquillage, douce et légère.",
        ingredientList: ["Farine de blé", "Beurre", "Œufs", "Sucre", "Levure", "Citron"],
        smallImageUrl: "https://example.com/images/madeleine_small.jpg",
        bigImageUrl: "https://example.com/images/madeleine_big.jpg",
        isAvailable: true
    },
    {
        productId: 12,
        productName: "Tartelette au citron",
        category: "Delices Sucré",
        categoryId: 2,
        price: "3,50 €",
        quantityInStock: 18,
        description: "Une petite tartelette garnie de crème au citron.",
        longDescription: "La tartelette au citron est une pâtisserie fraîche et acidulée, garnie d'une crème citron délicate sur une pâte sablée.",
        ingredientList: ["Farine de blé", "Beurre", "Sucre", "Œufs", "Citron", "Crème"],
        smallImageUrl: "https://example.com/images/tartelette_au_citron_small.jpg",
        bigImageUrl: "https://example.com/images/tartelette_au_citron_big.jpg",
        isAvailable: false
    },
    {
        productId: 13,
        productName: "Pain de mie complet",
        category: "Pain",
        categoryId: 1,
        price: "2,40 €",
        quantityInStock: 28,
        description: "Pain de mie à la farine complète.",
        longDescription: "Le pain de mie complet est plus nourrissant que le pain de mie traditionnel, avec un goût plus prononcé.",
        ingredientList: ["Farine complète", "Levure", "Sucre", "Sel", "Lait"],
        smallImageUrl: "https://example.com/images/pain_de_mie_complet_small.jpg",
        bigImageUrl: "https://example.com/images/pain_de_mie_complet_big.jpg",
        isAvailable: false
    },
    {
        productId: 14,
        productName: "Pain focaccia",
        category: "Pain",
        categoryId: 1,
        price: "3,00 €",
        quantityInStock: 10,
        description: "Pain plat italien à l'huile d'olive.",
        longDescription: "La focaccia est un pain plat italien, garni d'huile d'olive et de diverses herbes, souvent servi en entrée ou avec des plats de pâtes.",
        ingredientList: ["Farine de blé", "Levure", "Sel", "Eau", "Huile d'olive", "Romarin"],
        smallImageUrl: "https://example.com/images/pain_focaccia_small.jpg",
        bigImageUrl: "https://example.com/images/pain_focaccia_big.jpg",
        isAvailable: true
    },
    {
        productId: 15,
        productName: "Pain pita",
        category: "Pain",
        categoryId: 1,
        price: "1,50 €",
        quantityInStock: 50,
        description: "Pain plat utilisé pour les sandwichs.",
        longDescription: "Le pain pita est un pain plat et léger, parfait pour réaliser des sandwichs ou accompagner des plats orientaux.",
        ingredientList: ["Farine de blé", "Levure", "Sel", "Eau"],
        smallImageUrl: "https://example.com/images/pain_pita_small.jpg",
        bigImageUrl: "https://example.com/images/pain_pita_big.jpg",
        isAvailable: true
    },
    {
        productId: 16,
        productName: "Pain chapati",
        category: "Pain",
        categoryId: 1,
        price: "1,30 €",
        quantityInStock: 40,
        description: "Pain indien plat et rond.",
        longDescription: "Le chapati est un pain indien à base de farine de blé, cuit sur une plaque chaude.",
        ingredientList: ["Farine de blé", "Sel", "Eau"],
        smallImageUrl: "https://example.com/images/pain_chapati_small.jpg",
        bigImageUrl: "https://example.com/images/pain_chapati_big.jpg",
        isAvailable: true
      },
    {
        productId: 17,
        productName: "Tarte aux pommes",
        category: "Delices Sucré",
        categoryId: 2,
        price: "7,00 €",
        quantityInStock: 6,
        description: "Une tarte classique garnie de pommes caramélisées.",
        longDescription: "La tarte aux pommes est un dessert intemporel, préparé avec une pâte brisée croustillante et des pommes fraîches doucement caramélisées au four. Idéal pour terminer un repas ou accompagner une pause café.",
        ingredientList: ["Farine de blé", "Beurre", "Pommes", "Sucre", "Cannelle"],
        smallImageUrl: "https://example.com/images/tarte_aux_pommes_small.jpg",
        bigImageUrl: "https://example.com/images/tarte_aux_pommes_big.jpg",
        isAvailable: true
    },
    {
        productId: 18,
        productName: "Éclair au chocolat",
        category: "Delices Sucré",
        categoryId: 2,
        price: "3,00 €",
        quantityInStock: 15,
        description: "Un éclair gourmand garni de crème pâtissière au chocolat.",
        longDescription: "L'éclair au chocolat est une pâtisserie légère et savoureuse, composée d'une pâte à choux farcie de crème pâtissière au chocolat, le tout glacé avec une ganache brillante. Parfait pour les amateurs de chocolat.",
        ingredientList: ["Farine de blé", "Beurre", "Œufs", "Chocolat", "Sucre", "Crème"],
        smallImageUrl: "https://example.com/images/eclair_au_chocolat_small.jpg",
        bigImageUrl: "https://example.com/images/eclair_au_chocolat_big.jpg",
        isAvailable: true
    },
    {
        productId: 19,
        productName: "Croissant",
        category: "Delices Sucré",
        categoryId: 2,
        price: "1,50 €",
        quantityInStock: 40,
        description: "Un croissant au beurre doré et croustillant.",
        longDescription: "Le croissant est une viennoiserie emblématique, fabriquée à partir d'une pâte feuilletée levée généreusement beurrée. Sa texture croustillante et son goût riche en font un choix parfait pour le petit-déjeuner.",
        ingredientList: ["Farine de blé", "Beurre", "Levure", "Sucre", "Sel"],
        smallImageUrl: "https://example.com/images/croissant_small.jpg",
        bigImageUrl: "https://example.com/images/croissant_big.jpg",
        isAvailable: true
    },
    {
        productId: 20,
        productName: "Chocolatine",
        category: "Delices Sucré",
        categoryId: 2,
        price: "1,80 €",
        quantityInStock: 30,
        description: "Une viennoiserie moelleuse avec une double barre de chocolat.",
        longDescription: "Le pain au chocolat est une viennoiserie incontournable, connue pour sa pâte feuilletée moelleuse et ses deux barres de chocolat fondantes à l'intérieur. Un plaisir sucré idéal pour commencer la journée.",
        ingredientList: ["Farine de blé", "Beurre", "Chocolat", "Levure", "Sucre", "Sel"],
        smallImageUrl: "https://example.com/images/pain_au_chocolat_small.jpg",
        bigImageUrl: "https://example.com/images/pain_au_chocolat_big.jpg",
        isAvailable: true
    }
];
  